fix: docker-publish.yml cosign command line args when multiple tags are present
actions/starter-workflows pull request #1622
Opened 2022-06-28 07:09 UTC by jamesmoore

With scheduled builds the output docker image has two tags - branch name (eg, main) and nightly.

The current template is passing these as a single argument into the cosign sign command. This is causing failures of the workflow when run with a scheduled trigger.

This change splits them using xargs and runs multiple cosign commands, one for each tag.

Tested by running against one of my own repos, eg: https://github.com/jamesmoore/mp3info/runs/7087514897?check_suite_focus=true#step:8:2

2022-07-17 03:14 UTC, arnuphong approved these changes

2022-07-17 06:29 UTC, arnuphong requested changes

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> +        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
#1622

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> +        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
#1636

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> +        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
#202

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> +        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
#439

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> -        run: cosign sign ${{ steps.meta.outputs.tags }}@${{ steps.build-and-push.outputs.digest }}
@jamesmoore

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> -        run: cosign sign ${{ steps.meta.outputs.tags }}@${{ steps.build-and-push.outputs.digest }}
@josh

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
> -        run: cosign sign ${{ steps.meta.outputs.tags }}@${{ steps.build-and-push.outputs.digest }}
@arnuphong

2022-07-17 06:29 UTC, arnuphong commented on ci/docker-publish.yml
>            COSIGN_EXPERIMENTAL: "true"
.

2022-07-17 07:40 UTC, arnuphong approved these changes

2022-07-17 07:40 UTC, arnuphong commented on ci/docker-publish.yml
>          # against the sigstore community Fulcio instance.
[#1306](https://github.com/actions/starter-workflows/issues/1306)

2022-07-17 07:43 UTC, arnuphong reviewed
#

2022-07-26 10:31 UTC, CJCShadowsan approved these changes
works for me.

2022-07-27 10:45 UTC, Phantsure approved these changes
This seems to fix an issue. Confirmed my different people

2022-07-27 10:46 UTC, merged