Update old documentation links
actions/starter-workflows pull request #1777
Opened 2022-10-10 11:15 UTC by Phantsure

Addresses issue https://github.com/actions/starter-workflows/issues/1754

2022-10-16 02:55 UTC, ScottBrenner requested changes

2022-10-16 02:55 UTC, ScottBrenner commented on ci/swift.yml
> +# This workflow will build a golang project
```suggestion
# This workflow will build a Swift project
```

2022-10-18 12:49 UTC, Phantsure commented on ci/swift.yml
> +# This workflow will build a golang project
Thanks. Good catch

2022-10-19 18:06 UTC, anuragc617 approved these changes

2022-10-20 04:29 UTC, merged