chore: fix package(r) manager typo
actions/starter-workflows pull request #1994
Opened 2023-03-27 22:14 UTC by JoshuaKGoldberg

Spotted this little typo today. 🙂 

Co-authored-by: Rizèl Scarlet <blackgirlbytes@github.com>

2023-03-27 22:17 UTC, JamesMGreene approved these changes
Thank you for reporting the issue (we heard via @blackgirlbytes) _and_ submitting a quick PR to fix it! 😊 🎉 💝

2023-03-27 22:19 UTC, merged

2023-04-09 19:48 UTC, maddraddness requested changes
****

2024-04-15 00:12 UTC, RemedialGenius101 approved these changes

2024-04-15 00:12 UTC, RemedialGenius101 approved these changes

2024-04-15 00:16 UTC, RemedialGenius101 approved these changes

2024-04-15 00:17 UTC, RemedialGenius101 approved these changes

2024-04-15 03:00 UTC, Alexsito839 approved these changes
Te amo