update soos dash action commit hash
actions/starter-workflows pull request #2317
Opened 2024-02-28 17:36 UTC by SOOS-GSteen

update soos dash action commit hash

2024-03-28 22:03 UTC, alexisabril requested changes
Thank you @SOOS-GSteen for the PR! Apologies for the slow response and I've also added a newline at the end of this workflow. Would you update this PR with the latest `main`? This should otherwise be good to merge.

2024-03-28 22:03 UTC, alexisabril commented on code-scanning/soos-dast-scan.yml
>            sarif_file: results.sarif
```suggestion
          sarif_file: results.sarif

```

2024-03-29 13:20 UTC, SOOS-GSteen commented
> Thank you @SOOS-GSteen for the PR! Apologies for the slow response and I've also added a newline at the end of this workflow. Would you update this PR with the latest `main`? This should otherwise be good to merge.

All set @alexisabril - thanks again!

2024-03-29 16:06 UTC, alexisabril approved these changes

2024-04-01 20:11 UTC, merged

2024-12-02 08:36 UTC, 965022-oss commented
Merged CodeQL into action/workflow
from SHA f4dbb8424c

2025-01-06 05:49 UTC, 965022-oss commented
https://github.com/actions/starter-workflows/pull/2317#issue-2159481547/Merge #2317 Branch: main 965022-oss-patch1/SHA 3a95482282, label: update code scanning/soos-dast-scan.yml,

2025-02-18 23:39 UTC, Yedfree approved these changes