Updating dotnet CI starter workflows
actions/starter-workflows pull request #2333
Opened 2024-03-06 17:39 UTC by timheuer

This PR fixes #2332 by bumping action versions to `v4` where appropriate for checkout/setup commands (and `v2` for setup-msbuild).  This brings the starter workflows current and removes current warnings for deprecation around node versions in GitHub Actions

2024-03-06 22:04 UTC, alexisabril requested changes

2024-03-06 22:04 UTC, alexisabril commented on ci/dotnet-desktop.yml
> +      uses: actions/upload-artifact@v4
```suggestion
      uses: actions/upload-artifact@v3
```

Thank you for the update @timheuer! I'm recommending we keep `upload-artifact` at `v3` for the moment, as `v4` is not yet supported on GitHub Enterprise: https://github.com/marketplace/actions/upload-a-build-artifact#v4---whats-new

2024-03-07 01:43 UTC, DanRigby approved these changes

2024-03-12 19:08 UTC, alexisabril approved these changes

2024-03-12 19:08 UTC, merged

2024-03-25 04:30 UTC, w4nd3rhod3n approved these changes

2024-04-23 02:16 UTC, okorye reviewed
To opp out of these messages press this button here

2024-04-23 02:22 UTC, okorye commented
<Https://Facebook/Bradenbraidsandmore@gmail.com >


```

```To opt out of these messages please go to, https://Facebook/Bradenbraidsandmore@gmail.com ```

```

2026-03-14 22:46 UTC, yallgo236-code commented
###

2026-03-14 22:46 UTC, yallgo236-code commented
[README.md](https://github.com/user-attachments/files/26000235/README.md)

2026-11-13 13:49 UTC, hub966 approved these changes