Improve maven-publish.yml
actions/starter-workflows pull request #738
Opened 2020-12-07 23:33 UTC by Marcono1234

Fixes #539

- Remove redundant build step (`deploy` covers that anyways)
- Use long version of Maven command line parameter names
- Add `maven.install.skip=true` to skip installing artifact to local repository
Since the purpose of this workflow is to deploy the artifact, there is usually no need to install it to the local Maven repository. Though maybe there are use cases where this is desired; please let me know whether I should omit that.

The workflow seems to work fine, but it would be good if someone more familiar with Maven could have a look at as well.

2020-12-09 20:53 UTC, newblaque approved these changes

2020-12-13 05:52 UTC, kukulkankanpull requested changes
@Marcono1234  review required

2020-12-13 05:55 UTC, kukulkankanpull approved these changes
`#539`

2020-12-13 06:01 UTC, kukulkankanpull approved these changes

2020-12-13 06:01 UTC, kukulkankanpull commented
Marcono1234:marcono1234/maven-publish

2020-12-13 06:03 UTC, kukulkankanpull approved these changes

2020-12-15 01:09 UTC, andymckay approved these changes
Looks good to me @Marcono1234, I don't have maven experience enough to test it out though.

2021-04-04 19:14 UTC, johnperez416 approved these changes

2021-04-04 19:20 UTC, johnperez416 approved these changes

2021-06-11 09:40 UTC, kabat87 approved these changes

2021-12-09 14:58 UTC, breeze87j approved these changes

2022-03-18 04:29 UTC, closed without merging