actions/setup-elixir now lives under erlef GH Org
actions/starter-workflows pull request #822
Opened 2021-02-24 15:16 UTC by iautom8things

github.com/actions/setup-elixir is no longer maintained and now suggests using github.com/erlef/setup-elixir

This should be updated to help new Github Actions users to use the supported action.

2021-03-03 18:49 UTC, andymckay approved these changes
Thanks @iautom8things. This looks good to me, cc @jclem?

2021-03-03 19:10 UTC, andymckay requested changes
Actually... we'll need to pin this to a 40 char SHA instead of a version because its no longer in the actions repo.

2021-03-03 19:11 UTC, andymckay commented on ci/elixir.yml
> +      uses: erlef/setup-elixir@v1
```suggestion
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24

```

2021-03-05 15:16 UTC, jclem approved these changes
This looks good to me! Thanks for the PR @iautom8things.

2021-03-05 16:03 UTC, andymckay approved these changes

2021-03-05 16:03 UTC, merged

2021-03-05 16:05 UTC, iautom8things commented
Thank you @jclem and @andymckay!  🙏 ❤️ 💙 💚