add synopsys code scanning workflow
actions/starter-workflows pull request #835
Opened 2021-03-09 21:19 UTC by rahulguna10

This PR adds a new Code Scanning template workflow for Synopsys Intelligent Security Scan Action.

The Synopsys Intelligent Security Scan Action helps selectively perform SAST and SCA scans, triggered during a variety of GitHub Platform events, such as push or pull request. The Synopsys Intelligent Security Scan Action allows your projects to run the only required type of security scans, optimizing the time taken by security testing and provide quicker feedback on scan results.

Prerequisites
- To use this Action you must be a licensed Polaris customer.
- Intelligent scan server must be deployed and accessible via GitHub Actions.

## Pre-requisites

- [ ] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).

---

### **Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.**

---

## Tasks

**For _all_ workflows, the workflow:**

- [ ] Should be contained in a `.yml` file with the language or platform as its filename, in lower, [_kebab-cased_](https://en.wikipedia.org/wiki/Kebab_case) format (for example, [`docker-image.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml)).  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").
- [ ] Should use sentence case for the names of workflows and steps (for example, "Run tests").
- [ ] Should be named _only_ by the name of the language or platform (for example, "Go", not "Go CI" or "Go Build").
- [ ] Should include comments in the workflow for any parts that are not obvious or could use clarification.

**For _CI_ workflows, the workflow:**

- [ ] Should be preserved under [the `ci` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [ ] Should include a matching `ci/properties/*.properties.json` file (for example, [`ci/properties/docker-publish.properties.json`](https://github.com/actions/starter-workflows/blob/main/ci/properties/docker-publish.properties.json)).
- [ ] Should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [ ] Packaging workflows should run on `release` with `types: [ created ]`.
- [ ] Publishing workflows should have a filename that is the name of the language or platform, in lower case, followed by "-publish" (for example, [`docker-publish.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml)).

**For _Code Scanning_ workflows, the workflow:**

- [ ] Should be preserved under [the `code-scanning` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [ ] Should include a matching `code-scanning/properties/*.properties.json` file (for example, [`code-scanning/properties/codeql.properties.json`](https://github.com/actions/starter-workflows/blob/main/code-scanning/properties/codeql.properties.json)), with properties set as follows:
  - [ ] `name`: Name of the Code Scanning integration.
  - [ ] `organization`: Name of the organization producing the Code Scanning integration.
  - [ ] `description`: Short description of the Code Scanning integration.
  - [ ] `categories`: Array of languages supported by the Code Scanning integration.
  - [ ] `iconName`: Name of the SVG logo representing the Code Scanning integration. This SVG logo must be present in [the `icons` directory](https://github.com/actions/starter-workflows/tree/main/icons).
- [ ] Should run on `push` to `branches: [ $default-branch, $protected-branches ]` and `pull_request` to `branches: [ $default-branch ]`. We also recommend a `schedule` trigger of `cron: $cron-weekly` (for example, [`codeql.yml`](https://github.com/actions/starter-workflows/blob/c59b62dee0eae1f9f368b7011cf05c2fc42cf084/code-scanning/codeql.yml#L14-L21)).

**Some general notes:**

- [ ] This workflow must _only_ use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [ ] This workflow must _only_ use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We require that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [ ] Automation and CI workflows should not send data to any 3rd party service except for the purposes of installing dependencies.
- [ ] Automation and CI workflows cannot be dependent on a paid service or product.

2021-03-10 13:24 UTC, rahulguna10 commented on code-scanning/properties/synopsysio.properties.json
> +    "iconName": "synopsys",
When I change the iconName to synopsys-io, do I also need to rename the synopsys.svg to synopsys-io.svg ?

2021-03-10 13:35 UTC, nickfyson commented on code-scanning/properties/synopsysio.properties.json
> +    "iconName": "synopsys",
Yes, that's right.

Basically, for ease of understanding as we add more workflows all the files you're adding here should have the same name, eg....
- `synopsys-io.svg`
- `synopsys-io.yml`
- `synopsys-io.properties.json`

2021-03-10 13:38 UTC, rahulguna10 commented on code-scanning/properties/synopsysio.properties.json
> +    "iconName": "synopsys",
Got it.

2021-03-10 13:54 UTC, rahulguna10 commented on code-scanning/properties/synopsysio.properties.json
> +    "iconName": "synopsys",
I have pushed the changes @nickfyson

2021-03-11 18:46 UTC, nickfyson requested changes
Thanks for these updates!

The last thing we need is to use the full SHA rather than a tag to specify the workflow version, as that's a security requirement for actions that aren't under GitHub's direct control. I took the liberty of looking up the corresponding SHAs and adding them as suggested changes, but you might want to check for typos! 😆 

Then we'll be good to go! 🚀

2021-03-11 18:46 UTC, nickfyson commented on code-scanning/synopsys-io-actions.yml
> +      uses: synopsys-sig/intelligent-security-scan@v1
```suggestion
      uses: synopsys-sig/intelligent-security-scan@6940a88f5a0062304657dd62e7d3cee3b5bc9e57
```

2021-03-11 18:46 UTC, nickfyson commented on code-scanning/synopsys-io-actions.yml
> +      uses: synopsys-sig/intelligent-security-scan@v1
```suggestion
      uses: synopsys-sig/intelligent-security-scan@6940a88f5a0062304657dd62e7d3cee3b5bc9e57
```

2021-03-11 18:46 UTC, nickfyson commented on code-scanning/synopsys-io-actions.yml
> +      uses: blackducksoftware/github-action@v2
```suggestion
      uses: blackducksoftware/github-action@9ea442b34409737f64743781e9adc71fd8e17d38
```

2021-03-12 09:06 UTC, nickfyson commented on code-scanning/synopsys-io-actions.yml
> +      uses: blackducksoftware/github-action@v2
I think this is the appropriate SHA for this action? 🙂

2021-03-12 18:49 UTC, nickfyson approved these changes
LGTM 🙂

Thanks for the new workflow, and for jumping through all the (alas necessary) hoops! 😉

2021-03-12 18:55 UTC, merged