switch to official denoland/setup-deno action
actions/starter-workflows pull request #909
Opened 2021-05-19 12:06 UTC by lucacasonato

Also adds formatting and linting to the workflow (like dart workflow), and use uniform capitalization.

We released the denoland/setup-deno extension a few weeks ago in the https://github.com/denoland org as the official setup action.

2021-05-19 12:55 UTC, Express73 commented on ci/deno.yml
> -        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
Not happy

2021-05-19 13:37 UTC, Express73 requested changes

2021-05-24 13:59 UTC, frankgscott approved these changes

2021-05-24 20:01 UTC, joshmgross approved these changes
LGTM, thanks!

2021-05-24 20:02 UTC, merged